# Generated by Django 3.2.9 on 2021-11-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=255, unique=True, verbose_name='問題ID')),
                ('problem_name', models.CharField(max_length=255, verbose_name='問題名')),
                ('contest_id', models.CharField(max_length=255, verbose_name='コンテストID')),
                ('contest_name', models.CharField(max_length=255, verbose_name='コンテスト名')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=255, unique=True, verbose_name='提出ID')),
                ('submitter_accepted', models.IntegerField(verbose_name='提出者AC数')),
                ('submitted_at', models.DateTimeField(verbose_name='提出日時')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ranking.problem', verbose_name='問題')),
            ],
        ),
    ]
